### ISSUE TITLE
2017 2학기 서울대 결과물 정리

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#24]
고급인터페이스프로그래밍 (3학점)

정보문화학 전공자 중 선수과목(인터페이스 프로그래밍) 이수자

기간 : 2017년 9월 5일 ~ 2017년 12월 12일

시간 : 매주 화요일 9시 30 ~ 12시 30분 총 45시간

인원 : 7명

강사 : 윤성관

작품은 https://www.youtube.com/playlist?list=PLBjx8AiS7qA2rLOY-2q4-Cthq8NvW3HyZ

순서를 지켜주세요.

**Comment by hyoca** [comment]
완료
