### ISSUE TITLE
작품 순서 정리

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#25]
고려대 2018년 겨울 작품의 순서는 아래 플레이 리스트 순서와 동일 
https://www.youtube.com/playlist?list=PLBjx8AiS7qA3Jw9c736zvT4t7dL43zpFu
** 가즈아는 왜 리스트에 없나요?

중앙대 2018년 겨울 작품의 순서는 아래 플레이 리스트 순서와 동일
https://www.youtube.com/playlist?list=PLBjx8AiS7qA3Pn8YOT6gojXrHG3hXTGoI

**Comment by hyoca** [comment]
가즈아, 팀워크 추가, 순서정리 완료
