### ISSUE TITLE
고려대학교 2018 여름 수정

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#28]
Track 1  36시간
Track 2  84시간

입니다.

34명 - 33명 - 32명/12개 팀 - 31명 수료 이며, 

그리고 순서는, 

N찬 , 꿀루, BASKET MATCH, Busking, 띵동땡동, Ziggle, 암기하개
나머지 스크린 샷 예쁜 순으로 정렬해 주세요~

**Comment by ooodragon94** [comment]
수강신청 인원도 34명인가요?
추가적으로 지금 고려대 여름이 겨울꺼 복사를 한것 같은데,
1. 스크린샷이 없습니다 ㅠ 어플도 다릅니다
2. 파일 이름을 /2018_ku_summer.html 으로 바꾸도록 할까요?

**Comment by ooodragon94** [comment]
https://github.com/CodersHigh/WebSite/commit/aefc6490187e5c43c0eb3a8a61e52e79cdebda8a
