### ISSUE TITLE
중앙대학교 2018 수정

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#29]
Track 0 24시간
Track 1 39시간
Track 2 70시간

수료학생은

30 - 27 - 25/9팀 - 25/8팀

순서는, 

술케쥴 - 알바고 - 꾹꾹이 - N빵 - Hard Carrot - 암기스택 - Noty - Aplus 순으로 해 주시고, 

특별 발표로 지난 2기 OB 학생들 발표를 마지막에 넣을까해요.

**Comment by ooodragon94** [comment]
#39 b057504
꾹꾹이 자료가 없어서 넣었습니다!
OB 자료가 없습니다 ㅠ
