### ISSUE TITLE
강사소개에서 링크 에러

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#30]
박종영씨의 페이스북을 눌렀는데 고준일씨 페이지로 감.

버튼이 잘 못 붙은 거겠죠?

다른 강사들 링크는 잘 되는게, 이 것만 문제네요.

**Comment by ooodragon94** [comment]
https://github.com/CodersHigh/WebSite/commit/73ae881d8d9e89b2125a94fbcf3bc15c0fbe81b1
