### ISSUE TITLE
[모바일 CSS] 첫화면 하단 겹침

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#31]
![img_3826](https://user-images.githubusercontent.com/871180/44823507-c4d2d700-ac3b-11e8-8d6a-a6ea2384e763.PNG)

메인페이지 하단에 글자와 페이스북 링크가 겹침

**Comment by hyoca** [comment]
수정 완료.
마지막 커밋 
margin: 0 auto;
margin-bottom: 20px;
이 안먹고 있는데, 다음 커밋이 생기고 푸시하면 정상적으로 변할것으로 예상
