### ISSUE TITLE
[Mobile CSS] 학생 발표자료 유튜브 영상 짤림

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#32]
![img_3827](https://user-images.githubusercontent.com/871180/44824523-04e88880-ac41-11e8-8a9a-06e7397bb4cf.PNG)
![img_3831](https://user-images.githubusercontent.com/871180/44824524-05811f00-ac41-11e8-8585-52afb794f5b4.PNG)

모바일 폰에서 썸네일을 어떻게 보여줄지, 
눌렀을때 영상이 어떻게 재생되어야 할지에 대해 
UX적인 측면에서 먼저 고민하고 

고민한 내용을 이 이슈에 공유 부탁드려요

**Comment by hyoca** [comment]
저번에 있었던 페이스북페이지와 페이스북 그룹 임베드 이슈처럼,

접속한 유저의 디바이스를 자바스크립트로 먼저 확인하고 그에 맞게 iframe의 width를 100%(모바일)로 줄지, 아니면 지정해서(데스크탑) 줄지 정하면 될것같습니다.

**Comment by hyoca** [comment]
수정 완료 했습니다.
