### ISSUE TITLE
[Mobile CSS] 앱 스토어 배지

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#33]
![img_3828](https://user-images.githubusercontent.com/871180/44824720-2007c800-ac42-11e8-9e26-ee54a9e7d030.PNG)

모바일에서 앱 스토어 배지 레이아웃 수정해야 함

**Comment by hyoca** [comment]
수정 완료했습니다. 
추가로 깃헙, 웹페이지 이미지와 통일성을 맞추기 위해 기존 로고를 사과만 있는 로고로 변경하였습니다.
