### ISSUE TITLE
서울여대 페이지 수정

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#36]
- 유투브 링크 확인
- 전공&학년 무관 -> SW사관학교 대상학생

- https://codershigh.github.io/WebSite/reports_list.html 페이지의 고려대 겨율 -> 여름 , 동국대 -> 중앙대

**Comment by lingostar** [comment]
수정하면서, 

2018 1학기 한양대학교 iOS 특강 

은 2017년의 2017 1학기 한양대학교 공과대학 컴퓨터/SW 전공 와 동일하게 제목을 달아 주세요.

메인페이지에도 같이

**Comment by lingostar** [comment]
그리고 저 리스트를 보고 있으면, 네비게이션에 교육블로그가 선택되어 있어요.

페이지 구조를 다시 잡는 건 나중에 하고, 일단 저건 선택 해제 해 주세요.

**Comment by ooodragon94** [comment]
https://github.com/CodersHigh/WebSite/commit/25bfe02d28d654dba5b03688aa7fe45415fa5861
https://github.com/CodersHigh/WebSite/commit/9976273244a9dbfc0c8f9a6c32aefa6645a0d31e
https://github.com/CodersHigh/WebSite/commit/ec88847e16e6982b13fd369e2b131af4cf886011
