### ISSUE TITLE
페이지 Summary 문제

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#37]
![page_summary](https://user-images.githubusercontent.com/871180/44899556-0dbe8480-ad3d-11e8-99c3-d13b50f30267.png)

페북에 링크를 올리면 페북이 자동으로 위 그림과 같은 summary를 만들어요. 이게 본문의 시작점을 긁어와서 그런걸까요? 이 부분을 과정에 대한 정보로 바꾸려면 어떻게 해야 할까요?

**Comment by ooodragon94** [comment]
http://www.webconnoisseur.com/blog/social-networking/facebook-link-summary-snippets/
오늘내로

**Comment by ooodragon94** [comment]
![2018-09-05 4 27 47](https://user-images.githubusercontent.com/34847452/45077656-adf31f80-b128-11e8-9094-e241ea770a6f.png)

https://github.com/CodersHigh/WebSite/commit/7c4e54c752ecf699e89b2e8835167ca5d08d3edd
