### ISSUE TITLE
[Mobile CSS] 그림 설명 클래스

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/WebSite#44]
그림 아래에 설명용으로 사용할 문장의 클래스가 필요해서.
지금은 이탤릭을 쓰고 있는데, 
약간 회색으로 연하게 적혀도 좋을 것 같아요.
디자인적으로는 규원님과 상의해 주고 만들어지면 알려줘요.

혹시 기본 CSS에 있는데 내가 못 찾는 거면 알려줘요.

**Comment by hyoca** [comment]
저는 회색 글씨를 사용할때 
color: #777이나 #999를 거의 쓰고있습니다.
따로 css는 없는듯 하구요.

**Comment by lingostar** [comment]
@hyoca CSS에 한 추가해 줄래요?
